#!/usr/bin/env zsh
# Updates the envrc file in a git repo if PROJECT_NAME is not set
function project_name {
    function _append_project_name {
        print "export PROJECT_NAME=${PROJECT_NAME}" >> "${PROJECT_ENVRC_FILE}"
    }
    if [ -z "${PROJECT_NAME}" ]; then
        local GITROOT=$(git rev-parse --show-toplevel 2> /dev/null)
        if [ -n "${GITROOT}" ]; then
            local PROJECT_NAME="${GITROOT:t}"
            PROJECT_ENVRC_FILE="${GITROOT}/.envrc"
            if [ -e "${PROJECT_ENVRC_FILE}" ]; then
                rg -qe '^export PROJECT_NAME=' "${PROJECT_ENVRC_FILE}"
                if [ "$?" -ne 0 ]; then
                    _append_project_name
                    print -P "%F{red}.envrc updated.%f"
                fi
            else
                _append_project_name
            fi
        fi
    fi
}

precmd_functions=(project_name $precmd_functions)
